stages:
    - c++17-build
    - unit-test
    

make-c++17:
    stage: c++17-build
    script: make
    

    
catch-unit-tests:
    stage: unit-test
    script: 
            - cd tests
            - g++ UnitTests.cpp ../source/hangman*.cpp
            - ./a.out
